name: Build dnsmasq
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download dnsmasq source
      run: |
        wget https://thekelleys.org.uk/dnsmasq/dnsmasq-2.90.tar.gz
        tar -xzf dnsmasq-2.90.tar.gz
        cd dnsmasq-2.90
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Build dnsmasq
      run: |
        cd dnsmasq-2.90
        ./configure
        make
