name: Build dnsmasq
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf
    - name: Generate configure script
      run: autoreconf -i
    - name: Build dnsmasq
      run: |
        ./configure
        make
